language: node_js
sudo: false
node_js:
  - stable
  - 4
dist: trusty
before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
addons:
  chrome: stable
after_script:
  - npm run coveralls